# Generated by Django 4.2.21 on 2025-05-17 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'is_lecturer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='attendance.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='lecturers',
            field=models.ManyToManyField(limit_choices_to={'is_lecturer': True}, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='enrolled_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='qrcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.qrcode'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'qrcode')},
        ),
    ]
