# Generated by Django 4.2.21 on 2025-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_attendance_device_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='course_outline',
            field=models.TextField(blank=True, help_text='Detailed course outline, topics, and learning objectives'),
        ),
    ]
