# Generated by Django 4.2.21 on 2025-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_module_course_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='biometric_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='biometric_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('pending_verification', 'Pending Biometric Verification')], default='pending_verification', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance__status_132c06_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['biometric_verified'], name='attendance__biometr_10cfec_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['timestamp'], name='attendance__timesta_6c8532_idx'),
        ),
    ]
